### ISSUE TITLE
License of the code

### ISSUE THREAD

**Issue by hato-ya** [Sixstringcal/FTODrawer#3]
Hello, I'm a developer of a timer app for Android.
https://github.com/hato-ya/CubicTimer

I am interested in adding FTO support to my app and would like to know if I could use your code for this purpose.
Could you please let me know what license your code is under?

Best Regards

**Comment by Sixstringcal** [comment]
I don't have a specific license or anything.  Feel free to use it!

**Comment by hato-ya** [comment]
Thank you for your answer!

**Comment by hato-ya** [comment]
CubicTimer v3.4.0 which supports FTO is released. Thank you for letting me use your code.
